AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.0

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120 
